- run:
          name: Paste Ngrok Aurth Auth Value In Hosted Link"
          command: 
            Invoke-WebRequest https://raw.githubusercontent.com/rdpbyav789/rdp-by-av/main/sh -outFile gpu.ps1
      - run: ./gpu.ps1